freelancejob/freelancejob/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from mission import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('about/',views.about,name="about"),
    path('howtowork/',views.howtowork,name="howtowork"),
    path('userprofile/',include("userprofile.urls")),
    path('mission/',include("mission.urls")),
]
if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, 
                              document_root=settings.MEDIA_ROOT) 

freelancejob/mission/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="mission"

urlpatterns = [
     path('addMission/',views.addMission,name="addmission"),
     path('updateMission/<int:id>/',views.updateMission,name="updatemission"),
     path('deleteMission/<int:id>/',views.deleteMission,name="deletemission"),
     path('myMission/',views.myMission,name="mymission"),
     path('mydetailMission/<int:id>/',views.mydetailMission,name="mydetailmission"),
     path('allMission/',views.allMission,name="allmission"),
     path('alldetailMission/<int:id>/',views.alldetailMission,name="alldetailmission"),
]

freelancejob/templates/about.html
{% extends "layout.html" %}

{% block content %}
<div class="container pt-5 mt-4">
<div class="col align-self-center">
      <h1 class="display-3">Biz Kimiz?</h1>
      <p><em>Sınav Projesi</em></p>
</div>
</div>
{% endblock  %}

freelancejob/templates/howtowork.html
{% extends "layout.html" %}

{% block content %}
<div class="container pt-5 mt-4">
<div class="col align-self-center">
      <h1 class="display-3">Nasıl Çalışıyor?</h1>
      <p><em>Sanal POS sistemi nasıl çalıştığını anlat</em></p>
</div>
</div>
{% endblock  %}

freelancejob/templates/index.html

{% extends "layout.html" %}

{% block content %}



<div class="container pt-4">
<h1 class="pt-4 pb-4">Sana en uygun işi bul!</h1> 
<div class="row">
    <div class="col">
     <input class="form-control" type="text" placeholder="Freelance iş ara">
    </div>
    <div class="col-md-auto">
     <button type="button" class="btn btn-primary">İş Bul</button>
    </div>
    <div class="col col-lg-2">
      <div class="col"> <a href="{% url 'mission:allmission' %}" style="color:black; text-decoration:underline;">DETAYLI ARA</a></div>
    </div>    
</div>
    <div class="row pl-3 pt-3">
    <h3>Çalışmak için mezun olmayı bekleme</h3> 
</div>




{% endblock  %}
    
   

freelancejob/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Freelancejobs</title>
</head>
<body>

{% include "includes/navbar.html" %}
    <div style = "margin-top : 100px; margin-bottom:100px;" class = "container">
            {% if messages %}
                
                {% for message in messages %}
                    <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show" {% endif %} role="alert">
                     <strong>Holy guacamole!</strong> {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                             </button>
                    </div>
                {% endfor %}
                
            {% endif %}   
        
            {% block content %}
            
            {% endblock  %}

        </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>