freelancejob/freelancejob/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from mission import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('about/',views.about,name="about"),
    path('howtowork/',views.howtowork,name="howtowork"),
    path('userprofile/',include("userprofile.urls")),
    path('mission/',include("mission.urls")),
]
if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, 
                              document_root=settings.MEDIA_ROOT) 

freelancejob/mission/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="mission"

urlpatterns = [
     path('addMission/',views.addMission,name="addmission"),
     path('updateMission/<int:id>/',views.updateMission,name="updatemission"),
     path('deleteMission/<int:id>/',views.deleteMission,name="deletemission"),
     path('myMission/',views.myMission,name="mymission"),
     path('mydetailMission/<int:id>/',views.mydetailMission,name="mydetailmission"),
     path('allMission/',views.allMission,name="allmission"),
     path('alldetailMission/<int:id>/',views.alldetailMission,name="alldetailmission"),
]

freelancejob/userprofile/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="userprofile"

urlpatterns = [
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name="login"),
    path('logout/',views.logoutUser,name="logout"), 
    path('mypage/',views.mypage,name="mypage"),   
]

freelancejob/templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">
<div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">Freelancejobs</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'about' %}">Biz Kimiz?<span class="sr-only">(current)</span></a>
        </li>
         <li class="nav-item">
          <a class="nav-link" href="{% url 'howtowork' %}">Nasıl Çalışır?<span class="sr-only">(current)</span></a>
        </li>
      
      </ul> 
       {% if request.user.is_authenticated %}
        
          <div class="btn-group pr-3">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                     {{request.user.username}}
              </button>
              <div class="dropdown-menu">
              
              <a class="dropdown-item" href="{% url 'userprofile:mypage' %}">Sayfama Git</a>  
              <a class="dropdown-item" href="{% url 'mission:mymission' %}">İlanlarım</a>
              <a class="dropdown-item" href="#">Başvurularım</a>
              <a class="dropdown-item" href="#">Tamamladıklarım</a>
              <a class="dropdown-item" href="{% url 'mission:addmission' %}">Yeni Bir Görev Oluştur</a>
              <a class="dropdown-item" href="#">Profil Ayarları</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'userprofile:logout' %}">Çıkış Yap</a>
              </div>
            </div>
        {% else %}
              <a class="btn btn-outline-light mr-3" href="{% url 'userprofile:register' %}">Üye Ol</a>
              <a class="btn btn-outline-light mr-3" href="{% url 'userprofile:login' %}">Giriş Yap</a>
        {% endif %}
 </div>
</nav>