freelancejob/freelancejob/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from mission import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name="index"),
    path('about/',views.about,name="about"),
    path('howtowork/',views.howtowork,name="howtowork"),
    path('userprofile/',include("userprofile.urls")),
    path('mission/',include("mission.urls")),
]
if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, 
                              document_root=settings.MEDIA_ROOT) 

freelancejob/mission/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ="mission"

urlpatterns = [
     path('addMission/',views.addMission,name="addmission"),
     path('updateMission/<int:id>/',views.updateMission,name="updatemission"),
     path('deleteMission/<int:id>/',views.deleteMission,name="deletemission"),
     path('myMission/',views.myMission,name="mymission"),
     path('mydetailMission/<int:id>/',views.mydetailMission,name="mydetailmission"),
     path('allMission/',views.allMission,name="allmission"),
     path('alldetailMission/<int:id>/',views.alldetailMission,name="alldetailmission"),
]

freelancejob/mission/models.py
from django.db import models

#Category Model
class Category(models.Model):
    name = models.CharField(max_length=40,verbose_name="Kategori")
    slug = models.SlugField(max_length=40,unique=True)


    def __str__(self):
        return self.name

#Location Model
class Location(models.Model):
    name = models.CharField(max_length=50,verbose_name="Lokasyon")
    slug = models.SlugField(max_length=40,unique=True)

    def __str__(self):
        return self.name

#Mission Model
class Mission(models.Model):
    title = models.CharField(max_length=150,verbose_name="Başlık")
    category = models.ForeignKey(Category,on_delete=models.CASCADE,verbose_name="Kategori")
    location = models.ForeignKey(Location,on_delete=models.CASCADE,verbose_name="Lokasyon")
    createdBy = models.ForeignKey("auth.User",on_delete=models.CASCADE,default=1,verbose_name="Yayınlayan")
    mission = models.TextField(max_length=500,verbose_name="Görev Detayları")
    date = models.DateTimeField(auto_now_add=True,verbose_name="Yayınlandığı Tarih")
    budget = models.FloatField(null=True, blank=True, default=None,verbose_name="Bütçe")

    def __str__(self):
        return self.title
    class Meta:
        ordering= ["-date"]


freelancejob/mission/forms.py
from django import forms
from .models import Category,Location,Mission

class CategoryForm(forms.ModelForm):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False)


class LocationForm(forms.ModelForm):
    location = forms.ModelChoiceField(queryset=Location.objects.all(),required=False)


class MissionForm(forms.ModelForm):
    class Meta:
        model = Mission
        fields = ["title","category","location","mission","budget"]



freelancejob/mission/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .forms import MissionForm
from .models import Mission,Category,Location
from django.contrib import messages
from django.contrib.auth.decorators import login_required


#index sayfası
def index(request):
    return render(request,"index.html")

#about sayfası
def about(request):
    return render(request,"about.html")

#howtowork sayfası
def howtowork(request):
    return render(request,"howtowork.html")

#görev ekle sayfası
def addMission(request):

    form = MissionForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        mission = form.save()
        mission.createdBy=request.user
        mission.save()
        messages.success(request,"İlanınız yayınlandı.")
        return redirect("index")
    return render(request,"mission/addmission.html",{"form":form})

#görev update sayfası
def updateMission(request,id):
    update = Mission.objects.get(id=id)
    
    form = MissionForm(request.POST or None,request.FILES or None,instance=update)

    if form.is_valid():
        mission = form.save()
        mission.createdBy=request.user
        mission.save()
        
        messages.success(request,"İlanınız güncellendi")
        return redirect("mission:mymission")
    return render(request,"mission/updatemission.html",{"form":form})

#görev kaldır sayfası
def deleteMission(request,id):
    deletemission = Mission.objects.get(id=id)

    deletemission.delete()
    
    messages.success(request,"İlanınız yayından kaldırıldı")
    return redirect("mission:mymission")


#kullanıcının ilanlarının sayfası
def myMission(request):
    #author.id bunu bir dene
    mymissions = Mission.objects.filter(createdBy=request.user.id)
    context = {
        "mymissions":mymissions
    }

    return render(request,"mission/mymission.html",context)


#kullanıcının ilanlarının detaylandırma sayfası
def mydetailMission(request,id):
    detail = Mission.objects.get(id=id)
    
    return render(request,"mission/mydetailmission.html",{"detail":detail})


#ilan havuzu sayfası
def allMission(request):
    
    mymissions = Mission.objects.all()
    context = {
        "mymissions":mymissions
    }

    return render(request,"mission/allmission.html",context)


#ilan havuzundaki ilanların detaylandırma sayfası
def alldetailMission(request,id):
    detail = Mission.objects.get(id=id)
    
    return render(request,"mission/allmissiondetail.html",{"detail":detail})


freelancejob/templates/mission/addmission.html
{% extends "layout.html" %}

{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Görev Oluştur</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Görevi Oluştur</button>
        </form>
    </div>
  </div>

{% endblock  %}
    
   

freelancejob/templates/mission/allmission.html
{% extends "layout.html" %}

{% block content %}

<div class="container">
<div class="row">
    <div class="col-3 border border-primary shadow p-3 mb-5 bg-white rounded" style="height:500px;">
      filtreleme
    </div>
    <div class="col-9">
      {% for mymission in mymissions %}
      <div class="container border border-primary shadow p-3 mb-5 bg-white rounded" style="width:600px;">
       <p class="h4"><a href="{% url 'mission:alldetailmission' mymission.id %}" style="color:black; text-decoration: none;">{{mymission.title}}</a></p>
        <small> {{mymission.createdBy}} tarafından {{mymission.date}} tarihinde oluşturuldu</small> <a  class="btn btn-danger" href="{% url 'mission:alldetailmission' mymission.id %}">İlana Git</a>
        </div>
      

{% endfor %}
 


{% endblock  %}

freelancejob/templates/mission/allmissiondetail.html
{% extends "layout.html" %}

{% block content %}

<div class="container ">
  
  <div class="border border-primary p-3 mb-2 bg-primary text-white" style="height:90px;">
    <p class="h2">{{detail.title}}</p>
    <small>{{detail.date}} tarihinde {{detail.createdBy}} yayınlandı</small>
  </div>
  <div class="border border-primary p-3 mb-2 shadow p-3 mb-5 bg-white rounded" style="height:300px;">
    <p class="font-weight-normal">{{detail.mission}}</p>
  </div>

  <div style="position:absolute; right:150px;">
    <a href="" class="btn btn-danger btn-lg">Aday Ol</a>
  </div>  
</div>
{% endblock  %}

freelancejob/templates/mission/deletemission.html
<h2>silindi</h2>

freelancejob/templates/mission/missiondetail.html
{% extends "layout.html" %}

{% block content %}

<div class="container ">
  
  <div class="border border-primary p-3 mb-2 bg-primary text-white" style="height:90px;">
    <p class="h2">{{detail.title}}</p>
    <small>{{detail.date}} tarihinde {{detail.createdBy}} yayınlandı</small>
  </div>
  <div class="border border-primary p-3 mb-2 shadow p-3 mb-5 bg-white rounded" style="height:300px;">
    <p class="font-weight-normal">{{detail.mission}}</p>
  </div>

  <div style="position:absolute; right:150px;">
    <a href="" class="btn btn-danger btn-lg">Aday Ol</a>
  </div>  
</div>
{% endblock  %}

freelancejob/templates/mission/mydetailmission.html
{% extends "layout.html" %}

{% block content %}

<div class="container ">
  
  <div class="border border-primary p-3 mb-2 bg-primary text-white" style="height:90px;">
    <p class="h2">{{detail.title}}</p>
    <small>{{detail.date}} tarihinde yayınlandınız</small>
  </div>
  <div class="border border-primary p-3 mb-2 shadow p-3 mb-5 bg-white rounded" style="height:300px;">
    <p class="font-weight-normal">{{detail.mission}}</p>
  </div>

  <div style="position:absolute; right:150px;">
    <a href="" class="btn btn-danger btn-lg">Geri Dön</a>
  </div>  
</div>
{% endblock  %}

freelancejob/templates/mission/mymission.html
{% extends "layout.html" %}

{% block content %}

<table class="table">
  <thead class="thead-dark">
    <tr> 
      <th scope="col">İlan Başlığı</th>
      <th scope="col">Tarih</th>
      <th scope="col">Güncelle</th> 
      <th scope="col">Kaldır</th> 
    </tr>
  </thead>

  {% for mymission in mymissions  %}

  <tbody>
    <tr>
      
      <td><a href="{% url 'mission:mydetailmission' mymission.id %}" style="color:black; text-decoration: none;">{{mymission.title}}</a></td>
      <td>{{mymission.date}}</td>
      <td><a  class="btn btn-secondary" href="{% url 'mission:updatemission' mymission.id %}">İlanı Güncelle</a></td>
      <td><a  class="btn btn-danger" href="{% url 'mission:deletemission' mymission.id %}">İlanı Kaldır</a>  </td>
    </tr>  
  </tbody>
   
    {% endfor %}

</table>


{% endblock  %}

freelancejob/templates/mission/updatemission.html
{% extends "layout.html" %}

{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Görev Güncelle</h3>
        <hr>
        <form method = "post">
            {% csrf_token %}
            
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Görevi Güncelle</button>
        </form>
    </div>
  </div>

{% endblock  %}
    
   